### PR TITLE
Add Sindhi Language Support

### PR DESCRIPTION
**Pull request by sarwan920**
I have just Added Sindhi Language

### CODE REVIEW

**Comment by Mudassar045** [comment]
> I have just Added Sindhi Language

Good work @sarwan920 ! You should add an example of `Sindhi transliterate` in `README.md`

**Comment by sindresorhus** [comment]
Also make sure running `npm test` locally passes.

**Comment by sarwan920** [comment]
It passed local testing through npm test

**Comment by sarwan920** [comment]
Issues have been fixed

**Pull request closed without merging**
