### PR TITLE
Add Danish replacements

### PR DESCRIPTION
**Pull request by rhnorskov**
I've added replacements for the six Danish letters Æ, æ, Ø, ø, Å, and å.

Looking at each letter's usage, it doesn't appear to be in conflict with any other uses.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests are failing.

**Comment by sindresorhus** [comment]
You also need to add a test for this.

**Comment by sindresorhus** [comment]
> Looking at each letter's usage, it doesn't appear to be in conflict with any other uses.

Seems it does: https://github.com/sindresorhus/transliterate/pull/6/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddR66

So Danish needs to be disabled until #2 is done.

**Comment by rhnorskov** [comment]
I've disabled the replacements.
But what is your source of the latin replacements?
My research showed no use of the character not being transliterated to 'oe'.

**Comment by sindresorhus** [comment]
> But what is your source of the latin replacements?

I don't remember exactly, but I just tried using a latinize method I have in Swift that uses the system APIs (which are based on ICU) and it also converted `ø` to `o`.

**Pull request merged**
