### PR TITLE
Improve transliteration for russian language

### PR DESCRIPTION
**Pull request by Artemis69**
This transliteration uses [Yandex Maps](https://yandex.ru/support/nmaps/app_transliteration.html) transliteration schema which is easy to read and good in pronunciation.
And in that pull request i used tabs and single-quotes

### CODE REVIEW

**Comment by sindresorhus** [comment]
@AlexxNB Could you review?

**Comment by AlexxNB** [comment]
Personaly I don't like a variant for `ъе`->`y`. Russian word like `подъезд` will be `podyzd` and can't be phonetically read as original .  Current variant `podezd` is better choice. Or may be improved to `ъе`->`ye` and `podyezd` will have best match.

**Comment by AlexxNB** [comment]
Oh, it is look like @Artemis69 just have an error there
изображение

**Comment by Artemis69** [comment]
Oh, I think I was wrong. Sorry for the inconvenience

**Comment by AlexxNB** [comment]
No problem, just add the commit here to fix it. Other things are good replacements.

**Comment by Artemis69** [comment]
I hope I did everything right. I am newbie ＞﹏＜

**Comment by AlexxNB** [comment]
@Artemis69 I also thik that you should add `ъе` before `Е` declaration

**Comment by Artemis69** [comment]
@AlexxNB, yeah, you are right. Thanks!

**Comment by AlexxNB** [comment]
@sindresorhus now looks good for me

**Comment by sindresorhus** [comment]
Thanks to you both :)

**Pull request merged**
